(function(){
'use strict';
var N=6, MOVE_MS=92, CLEAR_MS=105, SPAWN_MS=58;
var COLORS=[
 {name:'BLUE',c:'#57a7ff',rgb:'87,167,255',light:'#a6d4ff',dark:'#285fc1',glow:'rgba(87,167,255,.5)'},
 {name:'PINK',c:'#ff5e9f',rgb:'255,94,159',light:'#ffafd2',dark:'#c62d6c',glow:'rgba(255,94,159,.46)'},
 {name:'GOLD',c:'#ffc84b',rgb:'255,200,75',light:'#ffe59c',dark:'#c78918',glow:'rgba(255,200,75,.45)'},
 {name:'VIOLET',c:'#9c7cff',rgb:'156,124,255',light:'#cbbaff',dark:'#6545c8',glow:'rgba(156,124,255,.48)'}
];
var $=function(id){return document.getElementById(id)};
var home=$('home'),game=$('game'),gridEl=$('grid'),board=$('board'),scoreEl=$('score'),bestMini=$('bestMini'),homeBest=$('homeBest'),homeStreak=$('homeStreak');
var fieldName=$('fieldName'),nextDot=$('nextDot'),phaseLabel=$('phaseLabel'),pressurePips=$('pressurePips'),runGoal=$('runGoal'),coach=$('coach'),sweep=$('sweep'),flash=$('flash'),toast=$('toast');
var pauseModal=$('pauseModal'),resultModal=$('resultModal'),goalsModal=$('goalsModal'),statsModal=$('statsModal'),settingsModal=$('settingsModal'),tutorialModal=$('tutorialModal');
var milestone=$('milestone'),unlock=$('unlock');
var cells=[];for(var i=0;i<36;i++){var cell=document.createElement('div');cell.className='cell';gridEl.appendChild(cell);cells.push(cell)}
var grid,balls,nextId,active,colorCursor,score=0,combo=0,bestCombo=0,turns=0,pressure=0,locked=false,ended=true,paused=false,revived=false,history=[],clearedRun=0,phaseIndex=0,mode='classic',dailyRng=null,runSeed=0,runCounted=false,countedScore=0,countedCleared=0,bestAtRunStart=0;
var settings={sound:true,music:true,motion:true,haptics:true,difficulty:'normal'};
var stats={best:0,games:0,totalScore:0,totalCleared:0,bestCombo:0,bestTurns:0,dailyStreak:0,lastDaily:'',dailyBest:0};
var achievements={firstClear:false,combo3:false,bigClear:false,score1000:false,survivor40:false,nova:false};
var runGoals=[],tutorialSeen=false,pendingStartMode=null;
function cleanNum(v){v=Number(v);return Number.isFinite(v)&&v>=0?v:0}
function normalizeStoredState(){['best','games','totalScore','totalCleared','bestCombo','bestTurns','dailyStreak','dailyBest'].forEach(function(k){stats[k]=cleanNum(stats[k])});if(typeof stats.lastDaily!=='string')stats.lastDaily=''}
function load(){try{var s=JSON.parse(localStorage.getItem('fs-settings')||'null');if(s)settings=Object.assign(settings,s);var st=JSON.parse(localStorage.getItem('fs-stats')||'null');if(st)stats=Object.assign(stats,st);var a=JSON.parse(localStorage.getItem('fs-ach')||'null');if(a)achievements=Object.assign(achievements,a);tutorialSeen=localStorage.getItem('fs-tutorial-seen')==='1'}catch(e){}normalizeStoredState();syncHome();syncSettings()}
function save(){try{localStorage.setItem('fs-settings',JSON.stringify(settings));localStorage.setItem('fs-stats',JSON.stringify(stats));localStorage.setItem('fs-ach',JSON.stringify(achievements))}catch(e){}}
function syncHome(){homeBest.textContent=stats.best;bestMini.textContent=stats.best;homeStreak.textContent=stats.dailyStreak;var today=dateKey();$('dailySubtitle').textContent=stats.lastDaily===today?'BEST '+stats.dailyBest+' • STREAK '+stats.dailyStreak:'NEW CHALLENGE TODAY'}
function syncSettings(){toggleVisual('soundToggle',settings.sound);toggleVisual('musicToggle',settings.music);toggleVisual('motionToggle',settings.motion);toggleVisual('hapticToggle',settings.haptics);var ds=document.querySelectorAll('[data-diff]');for(var i=0;i<ds.length;i++)ds[i].classList.toggle('selected',ds[i].dataset.diff===settings.difficulty)}
function toggleVisual(id,on){$(id).classList.toggle('on',!!on)}
function dateKey(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function seedFromString(s){var h=2166136261>>>0;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(){if(mode!=='daily')return Math.random();runSeed=(runSeed+0x6D2B79F5)>>>0;var t=runSeed;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}
function clone(v){return JSON.parse(JSON.stringify(v))}
function eachBall(fn){for(var id in balls)if(Object.prototype.hasOwnProperty.call(balls,id))fn(Number(id),balls[id])}
function snapshot(){return{grid:clone(grid),balls:clone(balls),nextId:nextId,active:active,colorCursor:colorCursor,score:score,combo:combo,bestCombo:bestCombo,turns:turns,pressure:pressure,clearedRun:clearedRun,phaseIndex:phaseIndex,runSeed:runSeed}}
function restore(s){grid=clone(s.grid);balls=clone(s.balls);nextId=s.nextId;active=s.active;colorCursor=s.colorCursor;score=s.score;combo=s.combo;bestCombo=s.bestCombo;turns=s.turns;pressure=s.pressure;clearedRun=s.clearedRun;phaseIndex=s.phaseIndex;runSeed=s.runSeed;ended=false;paused=false;locked=false;resultModal.classList.remove('show');render();updateUI()}
function ballCount(){var n=0;eachBall(function(){n++});return n}
function emptyCells(){var a=[];for(var y=0;y<N;y++)for(var x=0;x<N;x++)if(grid[y][x]===null)a.push([x,y]);return a}
function counts(){var a=[0,0,0,0];eachBall(function(id,b){a[b.color]++});return a}
function addBall(x,y,color){var id=nextId++;grid[y][x]=id;balls[id]={x:x,y:y,color:color};return id}
function colorsInPlay(){return phaseIndex>=2?4:3}
function setBallStyle(el,b){var c=COLORS[b.color];el.style.setProperty('--c',c.c);el.style.setProperty('--light',c.light);el.style.setProperty('--dark',c.dark);el.style.setProperty('--glow',c.glow)}
function render(spawned){spawned=spawned||[];for(var i=0;i<36;i++)cells[i].innerHTML='';eachBall(function(id,b){var el=document.createElement('div');el.className='piece';el.dataset.id=String(id);setBallStyle(el,b);if(b.color===active)el.classList.add('active');if(spawned.indexOf(id)>=0)el.classList.add('spawn');cells[b.y*N+b.x].appendChild(el)})}
function capture(){var out={},els=gridEl.querySelectorAll('.piece');for(var i=0;i<els.length;i++){var r=els[i].getBoundingClientRect();out[els[i].dataset.id]={x:r.left,y:r.top}}return out}
function animateMove(old){if(!settings.motion||!old)return;requestAnimationFrame(function(){var els=gridEl.querySelectorAll('.piece');for(var i=0;i<els.length;i++){var o=old[els[i].dataset.id];if(!o)continue;var r=els[i].getBoundingClientRect(),dx=o.x-r.left,dy=o.y-r.top;if(Math.abs(dx)<1&&Math.abs(dy)<1)continue;if(els[i].animate)els[i].animate([{transform:'translate3d('+dx+'px,'+dy+'px,0) scale(.98)'},{offset:.78,transform:'translate3d(0,0,0) scale(1.035)'},{transform:'translate3d(0,0,0) scale(1)'}],{duration:MOVE_MS,easing:'cubic-bezier(.16,.84,.28,1)'})}})}
function findGroups(color){var seen={},clear=[];eachBall(function(id,b){if(b.color!==color||seen[id])return;var q=[id],group=[];seen[id]=1;while(q.length){var cid=q.pop(),cb=balls[cid];group.push(cid);var ds=[[1,0],[-1,0],[0,1],[0,-1]];for(var d=0;d<4;d++){var nx=cb.x+ds[d][0],ny=cb.y+ds[d][1];if(nx<0||nx>=N||ny<0||ny>=N)continue;var nid=grid[ny][nx],nb=nid!==null?balls[nid]:null;if(nb&&nb.color===color&&!seen[nid]){seen[nid]=1;q.push(nid)}}}if(group.length>=3)clear=clear.concat(group)});return clear}
function groupSizeIfPlaced(x,y,color){var fake=999999;grid[y][x]=fake;balls[fake]={x:x,y:y,color:color};var q=[fake],seen={999999:1},size=0;while(q.length){var id=q.pop(),b=balls[id];size++;var ds=[[1,0],[-1,0],[0,1],[0,-1]];for(var d=0;d<4;d++){var nx=b.x+ds[d][0],ny=b.y+ds[d][1];if(nx<0||nx>=N||ny<0||ny>=N)continue;var nid=grid[ny][nx],nb=nid!==null?balls[nid]:null;if(nb&&nb.color===color&&!seen[nid]){seen[nid]=1;q.push(nid)}}}delete balls[fake];grid[y][x]=null;return size}
function spawnOne(){var e=emptyCells();if(!e.length)return null;var cs=counts(),numColors=colorsInPlay(),opts=[];for(var i=0;i<e.length;i++)for(var color=0;color<numColors;color++){var x=e[i][0],y=e[i][1],size=groupSizeIfPlaced(x,y,color);if(size>=3)continue;var neighbors=0,open=0,ds=[[1,0],[-1,0],[0,1],[0,-1]];for(var d=0;d<4;d++){var nx=x+ds[d][0],ny=y+ds[d][1];if(nx<0||nx>=N||ny<0||ny>=N)continue;if(grid[ny][nx]===null)open++;else neighbors++}var avg=ballCount()/numColors;var balance=Math.max(-1.2,Math.min(1.2,(avg-cs[color])*.22));var center=1-(Math.abs(x-2.5)+Math.abs(y-2.5))/5;var pairPenalty=size===2?-0.7:0;var v=rng()*2.8+balance+center*.38+neighbors*.12+pairPenalty;opts.push({x:x,y:y,color:color,v:v})}var pick;if(opts.length){opts.sort(function(a,b){return b.v-a.v});var top=opts.slice(0,Math.min(12,opts.length));pick=top[Math.floor(rng()*top.length)]}else{var p=e[Math.floor(rng()*e.length)];pick={x:p[0],y:p[1],color:Math.floor(rng()*numColors)}}return addBall(pick.x,pick.y,pick.color)}
function seedBoard(){for(var attempt=0;attempt<160;attempt++){grid=[];for(var y=0;y<N;y++){grid[y]=[];for(var x=0;x<N;x++)grid[y][x]=null}balls={};nextId=1;var diff=currentDifficulty(),initial=diff==='expert'?18:diff==='hard'?17:16;for(var k=0;k<initial;k++){var e=emptyCells(),p=e[Math.floor(rng()*e.length)],c=k%3;addBall(p[0],p[1],c)}if(!findGroups(0).length&&!findGroups(1).length&&!findGroups(2).length)return}}
function hasColor(color){var yes=false;eachBall(function(id,b){if(b.color===color)yes=true});return yes}
function legalColor(color){var yes=false,ds=[[1,0],[-1,0],[0,1],[0,-1]];eachBall(function(id,b){if(yes||b.color!==color)return;for(var d=0;d<4;d++){var nx=b.x+ds[d][0],ny=b.y+ds[d][1];if(nx>=0&&nx<N&&ny>=0&&ny<N&&grid[ny][nx]===null){yes=true;return}}});return yes}
function nextPlayable(from){var c=from,n=colorsInPlay();for(var i=0;i<n;i++){c=(c+1)%n;if(hasColor(c)&&legalColor(c))return c}return -1}
function fieldVars(color){var c=COLORS[color];document.documentElement.style.setProperty('--field',c.c);document.documentElement.style.setProperty('--field-rgb',c.rgb);document.documentElement.style.setProperty('--field-light',c.light);document.documentElement.style.setProperty('--field-dark',c.dark)}
function phaseFor(){if(turns>=42||score>=2200)return 3;if(turns>=28||score>=1050)return 2;if(turns>=14||score>=420)return 1;return 0}
var PHASES=[{name:'STABLE FIELD',milestone:'CHARGED'},{name:'CHARGED FIELD',milestone:'OVERDRIVE'},{name:'OVERDRIVE • VIOLET ONLINE',milestone:'CRITICAL'},{name:'CRITICAL FIELD',milestone:'CRITICAL'}];
function updatePhase(){var p=phaseFor();if(p>phaseIndex){phaseIndex=p;if(phaseIndex===2)introduceViolet();showMilestone(PHASES[phaseIndex].milestone);sfx('milestone');unlockAchievement('nova','FIELD EVOLVED','Reach Overdrive phase')}phaseLabel.textContent=PHASES[phaseIndex].name}
function introduceViolet(){var want=3;for(var i=0;i<want;i++){var id=spawnOne();if(id!==null){balls[id].color=3}}render()}
function currentDifficulty(){return mode==='daily'?'hard':settings.difficulty}
function pressureThreshold(){var diff=currentDifficulty();var base=diff==='expert'?2:diff==='hard'?2:3;if(phaseIndex>=1)base=Math.min(base,2);return base}
function nextSpawnCount(){pressure++;var count=1,t=pressureThreshold();if(pressure>=t){pressure=0;count=2}if(phaseIndex>=3&&turns%4===0)count=Math.max(count,2);return count}
function minBoardFloor(){return phaseIndex>=2?10:9}
function updateUI(){scoreEl.textContent=score;bestMini.textContent=stats.best;fieldVars(active);fieldName.textContent=COLORS[active].name;var next=nextPlayable(colorCursor);if(next<0)next=active;nextDot.style.background=COLORS[next].c;nextDot.style.color=COLORS[next].c;phaseLabel.textContent=PHASES[phaseIndex].name;var ps=pressurePips.children,t=pressureThreshold();for(var i=0;i<ps.length;i++)ps[i].className=(i<pressure?'on ':'')+(pressure>=t-1&&i<pressure?'hot':'');runGoal.innerHTML='GOAL <strong>'+clearedRun+'/15</strong>';updateGoalProgress()}
function performMove(dx,dy){var list=[];eachBall(function(id,b){if(b.color===active)list.push({id:id,b:b,ox:b.x,oy:b.y})});list.sort(function(a,b){if(dx<0)return a.ox-b.ox;if(dx>0)return b.ox-a.ox;if(dy<0)return a.oy-b.oy;return b.oy-a.oy});var moved=false;for(var i=0;i<list.length;i++){var it=list[i],b=it.b;grid[b.y][b.x]=null;var x=b.x,y=b.y;while(true){var nx=x+dx,ny=y+dy;if(nx<0||nx>=N||ny<0||ny>=N||grid[ny][nx]!==null)break;x=nx;y=ny}b.x=x;b.y=y;grid[y][x]=it.id;if(x!==it.ox||y!==it.oy)moved=true}return moved}
function fieldSweep(dx,dy){if(!settings.motion)return;var c=COLORS[active],angle=dx>0?'to right':dx<0?'to left':dy>0?'to bottom':'to top';sweep.style.background='linear-gradient('+angle+',transparent 18%,rgba('+c.rgb+',.42),rgba(255,255,255,.16),transparent 72%)';sweep.style.setProperty('--sx',(dx<0?'28px':dx>0?'-28px':'0'));sweep.style.setProperty('--sy',(dy<0?'28px':dy>0?'-28px':'0'));sweep.style.setProperty('--ex',(dx<0?'-18px':dx>0?'18px':'0'));sweep.style.setProperty('--ey',(dy<0?'-18px':dy>0?'18px':'0'));sweep.classList.remove('go');void sweep.offsetWidth;sweep.classList.add('go')}
function boardFlash(){if(!settings.motion)return;flash.classList.remove('go');void flash.offsetWidth;flash.classList.add('go')}
function bump(){board.classList.remove('shake');void board.offsetWidth;board.classList.add('shake');sfx('blocked');haptic('error')}
function showToast(text){toast.textContent=text;toast.classList.remove('show');void toast.offsetWidth;toast.classList.add('show')}
function scorePop(){scoreEl.classList.remove('score-pop');void scoreEl.offsetWidth;scoreEl.classList.add('score-pop')}
function particles(ids){if(!settings.motion)return;for(var i=0;i<ids.length;i++){var el=gridEl.querySelector('[data-id="'+ids[i]+'"]');if(!el||!balls[ids[i]])continue;var r=el.getBoundingClientRect(),col=COLORS[balls[ids[i]].color].c;for(var k=0;k<4;k++){var p=document.createElement('i');p.className='particle';p.style.background=col;p.style.left=(r.left+r.width/2)+'px';p.style.top=(r.top+r.height/2)+'px';p.style.setProperty('--dx',((rng()-.5)*68)+'px');p.style.setProperty('--dy',((rng()-.5)*68)+'px');document.body.appendChild(p);setTimeout((function(x){return function(){x.remove()}})(p),390)}if(i===0){var ring=document.createElement('i');ring.className='ringfx';ring.style.color=col;ring.style.left=(r.left+r.width/2)+'px';ring.style.top=(r.top+r.height/2)+'px';document.body.appendChild(ring);setTimeout((function(x){return function(){x.remove()}})(ring),450)}}}
function resolveSwipe(dx,dy){if(locked||ended||paused)return;unlockAudio();locked=true;var before=snapshot(),old=capture();if(!performMove(dx,dy)){locked=false;bump();return}history.push(before);if(history.length>12)history.shift();turns++;fieldSweep(dx,dy);render();animateMove(old);sfx('swipe');haptic('light');setTimeout(function(){var clear=findGroups(active);if(clear.length){combo++;bestCombo=Math.max(bestCombo,combo);clearedRun+=clear.length;pressure=Math.max(0,pressure-1);var gain=clear.length*10*combo;score+=gain;scorePop();showToast('+'+gain+(combo>1?' • COMBO ×'+combo:''));particles(clear);boardFlash();sfx(clear.length>=5?'bigclear':combo>=2?'combo':'clear');haptic(clear.length>=5?'success':'medium');if(clear.length>=5)unlockAchievement('bigClear','POWER CLEAR','Clear 5 or more at once');if(combo>=3)unlockAchievement('combo3','CHAIN REACTION','Reach a ×3 combo');unlockAchievement('firstClear','FIRST CONTACT','Make your first clear');for(var i=0;i<clear.length;i++){var el=gridEl.querySelector('[data-id="'+clear[i]+'"]');if(el)el.classList.add(clear.length>=5?'superclear':'clear')}advanceFieldImmediately();setTimeout(function(){for(var j=0;j<clear.length;j++){var b=balls[clear[j]];if(b){grid[b.y][b.x]=null;delete balls[clear[j]]}}rebalanceAfterClear(function(){finishTurn(true)})},CLEAR_MS)}else{combo=0;spawnMany(nextSpawnCount(),0,function(){finishTurn(false)})}},MOVE_MS)}
function advanceFieldImmediately(){var oldActive=active;var candidate=nextPlayable(colorCursor);if(candidate>=0){active=candidate;colorCursor=candidate;fieldVars(active);fieldName.textContent=COLORS[active].name;var next=nextPlayable(colorCursor);if(next<0)next=active;nextDot.style.background=COLORS[next].c;nextDot.style.color=COLORS[next].c;renderActiveOnly(oldActive)}}
function renderActiveOnly(){var els=gridEl.querySelectorAll('.piece');for(var i=0;i<els.length;i++){var b=balls[els[i].dataset.id];els[i].classList.toggle('active',b&&b.color===active)}}
function spawnMany(total,index,done){if(index>=total){if(done)done();return}var id=spawnOne();if(id===null){endGame();return}render([id]);sfx('spawn');setTimeout(function(){spawnMany(total,index+1,done)},SPAWN_MS)}
function rebalanceAfterClear(done){var floor=minBoardFloor(),need=Math.min(2,Math.max(0,floor-ballCount()));if(need>0){showToast('FIELD REBALANCE');spawnMany(need,0,done)}else done()}
function finishTurn(fromClear){updatePhase();if(score>=1000)unlockAchievement('score1000','FOUR DIGITS','Score 1,000 points');if(turns>=40)unlockAchievement('survivor40','SURVIVOR','Reach 40 swipes');var currentValid=hasColor(active)&&legalColor(active);if(!currentValid){var n=nextPlayable(colorCursor);if(n<0){endGame();return}active=n;colorCursor=n}render();updateUI();locked=false}
function showMilestone(text){$('milestoneText').textContent=text;milestone.classList.remove('show');void milestone.offsetWidth;milestone.classList.add('show')}
function newRunGoals(){runGoals=[{id:'clear',label:'Clear 15 balls',target:15},{id:'combo',label:'Reach combo ×3',target:3},{id:'survive',label:'Survive 30 swipes',target:30}]}
function goalValue(g){var v=g.id==='clear'?clearedRun:g.id==='combo'?bestCombo:turns;return Number.isFinite(v)?v:0}
function updateGoalProgress(){if(!runGoals.length)newRunGoals();var activeRun=game.classList.contains('show')&&!ended,html='';for(var i=0;i<runGoals.length;i++){var g=runGoals[i],raw=activeRun?goalValue(g):0,v=Math.max(0,Math.min(g.target,cleanNum(raw))),label=activeRun?(v+'/'+g.target):'READY';html+='<div class="challenge"><div class="challenge-top"><span>'+g.label+'</span><span>'+label+'</span></div><div class="bar"><i style="width:'+(activeRun?(v/g.target*100):0)+'%"></i></div></div>'}$('challengeList').innerHTML=html}
function startGame(nextMode){mode=nextMode||'classic';if(mode==='daily'){runSeed=seedFromString('fieldshift-'+dateKey())}else runSeed=(Date.now()>>>0);phaseIndex=0;seedBoard();score=0;combo=0;bestCombo=0;turns=0;pressure=0;locked=false;ended=false;paused=false;revived=false;history=[];clearedRun=0;runCounted=false;countedScore=0;countedCleared=0;bestAtRunStart=stats.best;colorCursor=-1;active=nextPlayable(-1);if(active<0)active=0;colorCursor=active;newRunGoals();home.classList.remove('show');pauseModal.classList.remove('show');resultModal.classList.remove('show');game.classList.add('show');coach.style.opacity='1';fieldVars(active);render();updateUI();unlockAudio();if(settings.music)startAmbience();sfx('start')}
function endGame(){if(ended)return;ended=true;locked=false;stopAmbience();if(!runCounted){stats.games++;runCounted=true}else{stats.totalScore-=countedScore;stats.totalCleared-=countedCleared}stats.totalScore+=score;stats.totalCleared+=clearedRun;countedScore=score;countedCleared=clearedRun;stats.bestCombo=Math.max(stats.bestCombo,bestCombo);stats.bestTurns=Math.max(stats.bestTurns,turns);var isNew=score>bestAtRunStart;if(score>stats.best)stats.best=score;if(mode==='daily')completeDaily();save();syncHome();$('resultScore').textContent=score;$('resultTurns').textContent=turns;$('resultCombo').textContent=bestCombo;$('resultClears').textContent=clearedRun;$('newBest').classList.toggle('show',isNew);$('rewindBtn').style.display=!revived&&history.length>=3?'block':'none';sfx('gameover');haptic('error');setTimeout(function(){resultModal.classList.add('show')},120)}
function completeDaily(){var today=dateKey();stats.dailyBest=Math.max(stats.lastDaily===today?stats.dailyBest:0,score);if(stats.lastDaily!==today){var d=new Date();d.setDate(d.getDate()-1);var y=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');stats.dailyStreak=stats.lastDaily===y?stats.dailyStreak+1:1;stats.lastDaily=today}}
function rewind(){if(revived||history.length<3)return;var s=history[Math.max(0,history.length-3)];restore(s);revived=true;history=[];showToast('FIELD REWOUND');sfx('rewind')}
function showHome(){stopAmbience();ended=true;paused=false;game.classList.remove('show');pauseModal.classList.remove('show');resultModal.classList.remove('show');home.classList.add('show');syncHome()}
function showGoals(inRun){$('goalsTitle').textContent=inRun?'Run Goals':'Goals';$('goalsSub').textContent=inRun?'Progress updates live during this run.':'Simple goals that reward mastery, not grinding.';updateGoalProgress();goalsModal.classList.add('show')}
var ACH_META={firstClear:['FIRST CONTACT','Make your first clear'],combo3:['CHAIN REACTION','Reach a ×3 combo'],bigClear:['POWER CLEAR','Clear 5 or more at once'],score1000:['FOUR DIGITS','Score 1,000 points'],survivor40:['SURVIVOR','Reach 40 swipes'],nova:['FIELD EVOLVED','Reach Overdrive phase']};
function unlockAchievement(id,title,text){if(achievements[id])return;achievements[id]=true;save();$('unlockTitle').textContent=title;$('unlockText').textContent=text;unlock.classList.remove('show');void unlock.offsetWidth;unlock.classList.add('show');sfx('achievement')}
function renderStats(){normalizeStoredState();var avg=stats.games?Math.round(stats.totalScore/stats.games):0,empty=stats.games===0;$('statsGrid').innerHTML=(empty?'<div class="empty-state" style="grid-column:1/-1">Play your first run to start building your FieldShift history.</div>':'')+'<div class="stat-card">BEST SCORE<strong>'+stats.best+'</strong></div><div class="stat-card">GAMES<strong>'+stats.games+'</strong></div><div class="stat-card">AVG SCORE<strong>'+avg+'</strong></div><div class="stat-card">BALLS CLEARED<strong>'+stats.totalCleared+'</strong></div><div class="stat-card">BEST COMBO<strong>×'+stats.bestCombo+'</strong></div><div class="stat-card">LONGEST RUN<strong>'+stats.bestTurns+'</strong></div>';var h='';for(var id in ACH_META){var m=ACH_META[id];h+='<div class="ach '+(achievements[id]?'unlocked':'')+'"><div class="ach-icon">'+(achievements[id]?'✦':'○')+'</div><div class="ach-copy"><strong>'+m[0]+'</strong><small>'+m[1]+'</small></div></div>'}$('achievementList').innerHTML=h}
function shareScore(){var text='I scored '+score+' in FieldShift with a ×'+bestCombo+' combo.';if(navigator.share)navigator.share({title:'FieldShift',text:text}).catch(function(){});else{navigator.clipboard&&navigator.clipboard.writeText(text);showToast('SCORE COPIED')}}

/* AUDIO: procedural, normalized and mobile-resume safe */
var audioCtx=null,master=null,limiter=null,sfxBus=null,musicBus=null,ambienceNodes=[],audioReadyPromise=null;
function createAudioGraph(){if(audioCtx)return;var AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audioCtx=new AC();master=audioCtx.createGain();sfxBus=audioCtx.createGain();musicBus=audioCtx.createGain();limiter=audioCtx.createDynamicsCompressor();master.gain.value=.92;sfxBus.gain.value=.86;musicBus.gain.value=.13;limiter.threshold.value=-8;limiter.knee.value=8;limiter.ratio.value=14;limiter.attack.value=.003;limiter.release.value=.18;sfxBus.connect(master);musicBus.connect(master);master.connect(limiter);limiter.connect(audioCtx.destination)}
function unlockAudio(done){if(!settings.sound&&!settings.music){done&&done();return}try{createAudioGraph();if(!audioCtx){done&&done();return}if(audioCtx.state==='running'){done&&done();return}if(!audioReadyPromise){var r=audioCtx.resume();audioReadyPromise=r&&r.then?r.catch(function(){}):Promise.resolve();audioReadyPromise=audioReadyPromise.then(function(){audioReadyPromise=null})}audioReadyPromise.then(function(){done&&done()})}catch(e){audioReadyPromise=null;done&&done()}}
function tone(freq,dur,type,vol,delay){if(!settings.sound||!audioCtx||!sfxBus||audioCtx.state!=='running')return;var o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+(delay||0),peak=Math.max(.001,Math.min(.38,vol||.11));o.type=type||'sine';o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(peak,t+.006);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(sfxBus);o.start(t);o.stop(t+dur+.025)}
function noise(dur,vol,freq){if(!settings.sound||!audioCtx||!sfxBus||audioCtx.state!=='running')return;var len=Math.max(1,Math.floor(audioCtx.sampleRate*dur)),buf=audioCtx.createBuffer(1,len,audioCtx.sampleRate),data=buf.getChannelData(0);for(var i=0;i<len;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/len,2);var src=audioCtx.createBufferSource(),filter=audioCtx.createBiquadFilter(),g=audioCtx.createGain();src.buffer=buf;filter.type='bandpass';filter.frequency.value=freq||1150;filter.Q.value=.7;g.gain.value=vol||.05;src.connect(filter);filter.connect(g);g.connect(sfxBus);src.start()}
function playSfxNow(name){switch(name){case'start':tone(330,.08,'sine',.15);tone(494,.12,'sine',.13,.045);break;case'swipe':tone(145,.045,'triangle',.09);tone(230,.025,'sine',.045,.012);break;case'blocked':tone(110,.065,'triangle',.11);noise(.04,.035,600);break;case'spawn':tone(275,.055,'sine',.09);tone(410,.045,'sine',.045,.018);break;case'clear':tone(430,.075,'sine',.18);tone(650,.11,'sine',.15,.03);noise(.06,.055,1500);break;case'combo':tone(520,.065,'sine',.19);tone(770,.095,'sine',.17,.026);tone(1020,.13,'sine',.14,.055);noise(.055,.035,1900);break;case'bigclear':tone(390,.075,'triangle',.21);tone(660,.105,'sine',.19,.026);tone(950,.145,'sine',.17,.055);tone(1280,.12,'sine',.10,.09);noise(.10,.075,1700);break;case'milestone':tone(440,.11,'sine',.16);tone(660,.15,'sine',.16,.065);tone(880,.20,'sine',.15,.13);break;case'achievement':tone(700,.075,'sine',.14);tone(940,.12,'sine',.15,.055);tone(1180,.14,'sine',.09,.1);break;case'gameover':tone(270,.13,'triangle',.15);tone(195,.19,'triangle',.13,.09);tone(135,.27,'triangle',.11,.20);break;case'rewind':tone(720,.08,'sine',.14);tone(540,.09,'sine',.13,.045);tone(370,.13,'sine',.12,.095);break;}}
function sfx(name){if(!settings.sound)return;unlockAudio(function(){playSfxNow(name)})}
function startAmbience(){stopAmbience();if(!settings.music)return;unlockAudio(function(){if(!audioCtx||!musicBus||audioCtx.state!=='running'||!settings.music)return;try{var g=audioCtx.createGain(),filter=audioCtx.createBiquadFilter();g.gain.value=.55;filter.type='lowpass';filter.frequency.value=310;filter.Q.value=.35;g.connect(filter);filter.connect(musicBus);var o1=audioCtx.createOscillator(),o2=audioCtx.createOscillator();o1.type='sine';o2.type='triangle';o1.frequency.value=55;o2.frequency.value=82.5;o1.connect(g);o2.connect(g);o1.start();o2.start();ambienceNodes=[o1,o2,g,filter]}catch(e){}})}
function stopAmbience(){for(var i=0;i<ambienceNodes.length;i++){try{ambienceNodes[i].stop&&ambienceNodes[i].stop()}catch(e){}try{ambienceNodes[i].disconnect&&ambienceNodes[i].disconnect()}catch(e){}}ambienceNodes=[]}
function resumeAudioAfterInterruption(){if((settings.sound||settings.music)&&audioCtx&&audioCtx.state!=='running')unlockAudio(function(){if(settings.music&&game.classList.contains('show')&&!ended&&!ambienceNodes.length)startAmbience()})}
/* HAPTICS: arbitrary iOS game haptics are unavailable on current Safari. Android vibrates; direct-tap controls get native iOS switch taps below. */
function haptic(kind){if(!settings.haptics)return;try{if(navigator.vibrate){var p=kind==='error'?[18,24,24]:kind==='success'?[14,18,35]:kind==='medium'?18:8;navigator.vibrate(p)}}catch(e){}}
function installIOSButtonHaptics(){/* iOS 26.5+ blocks programmatic gameplay haptics. Native Swift build will provide full Core Haptics. */}

function showTutorial(startMode){pendingStartMode=startMode||null;$('tutorialActionBtn').textContent=pendingStartMode?'Start Playing':'Got it';settingsModal.classList.remove('show');tutorialModal.classList.add('show')}
function finishTutorial(){tutorialSeen=true;try{localStorage.setItem('fs-tutorial-seen','1')}catch(e){}tutorialModal.classList.remove('show');var m=pendingStartMode;pendingStartMode=null;if(m)startGame(m)}
function requestStart(m){unlockAudio();if(!tutorialSeen)showTutorial(m);else startGame(m)}

/* controls */
$('playBtn').addEventListener('click',function(){requestStart('classic')});$('dailyBtn').addEventListener('click',function(){requestStart('daily')});$('tutorialBtn').addEventListener('click',function(){showTutorial(null)});$('settingsTutorialBtn').addEventListener('click',function(){showTutorial(null)});$('tutorialActionBtn').addEventListener('click',finishTutorial);
$('pauseBtn').addEventListener('click',function(){if(locked)return;paused=true;pauseModal.classList.add('show');sfx('swipe')});$('resumeBtn').addEventListener('click',function(){paused=false;pauseModal.classList.remove('show')});$('restartBtn').addEventListener('click',function(){startGame(mode)});$('homeBtn').addEventListener('click',showHome);$('resultHomeBtn').addEventListener('click',showHome);$('againBtn').addEventListener('click',function(){resultModal.classList.remove('show');startGame(mode)});$('rewindBtn').addEventListener('click',rewind);$('shareBtn').addEventListener('click',shareScore);
$('challengesBtn').addEventListener('click',function(){if(!runGoals.length)newRunGoals();showGoals(false)});$('goalsInRunBtn').addEventListener('click',function(){pauseModal.classList.remove('show');showGoals(true)});$('closeGoalsBtn').addEventListener('click',function(){goalsModal.classList.remove('show');if(game.classList.contains('show')&&!ended){paused=false}});
$('statsBtn').addEventListener('click',function(){renderStats();statsModal.classList.add('show')});$('closeStatsBtn').addEventListener('click',function(){statsModal.classList.remove('show')});$('settingsBtn').addEventListener('click',function(){syncSettings();settingsModal.classList.add('show')});$('closeSettingsBtn').addEventListener('click',function(){settingsModal.classList.remove('show');save()});
$('soundToggle').addEventListener('click',function(){settings.sound=!settings.sound;toggleVisual('soundToggle',settings.sound);if(settings.sound)unlockAudio(function(){playSfxNow('start')})});$('musicToggle').addEventListener('click',function(){settings.music=!settings.music;toggleVisual('musicToggle',settings.music);if(settings.music&&game.classList.contains('show'))startAmbience();else stopAmbience()});$('motionToggle').addEventListener('click',function(){settings.motion=!settings.motion;toggleVisual('motionToggle',settings.motion)});$('hapticToggle').addEventListener('click',function(){settings.haptics=!settings.haptics;toggleVisual('hapticToggle',settings.haptics)});
var diffBtns=document.querySelectorAll('[data-diff]');for(var di=0;di<diffBtns.length;di++)diffBtns[di].addEventListener('click',function(){settings.difficulty=this.dataset.diff;syncSettings()});
var sx=0,sy=0,drag=false,area=$('gestureArea');function begin(x,y){sx=x;sy=y;drag=true}function finish(x,y){if(!drag)return;drag=false;var dx=x-sx,dy=y-sy;if(Math.sqrt(dx*dx+dy*dy)<24){bump();return}if(Math.abs(dx)>Math.abs(dy))resolveSwipe(dx>0?1:-1,0);else resolveSwipe(0,dy>0?1:-1)}area.addEventListener('touchstart',function(e){var t=e.changedTouches[0];begin(t.clientX,t.clientY);e.preventDefault()},{passive:false});area.addEventListener('touchend',function(e){var t=e.changedTouches[0];finish(t.clientX,t.clientY);e.preventDefault()},{passive:false});area.addEventListener('touchcancel',function(){drag=false});area.addEventListener('mousedown',function(e){begin(e.clientX,e.clientY)});window.addEventListener('mouseup',function(e){finish(e.clientX,e.clientY)});
window.addEventListener('error',function(e){console.error('FieldShift error',e.error||e.message)});document.addEventListener('visibilitychange',function(){if(!document.hidden)resumeAudioAfterInterruption()});window.addEventListener('pageshow',resumeAudioAfterInterruption);document.addEventListener('touchstart',function(){if(audioCtx&&audioCtx.state!=='running')resumeAudioAfterInterruption()},{passive:true});
load();newRunGoals();updateGoalProgress();renderStats();installIOSButtonHaptics();
})();
