(function(){
'use strict';
var state=window.__FS15_SOUND__||{enabled:true};
var AC=window.AudioContext||window.webkitAudioContext;
var ctx=null,master=null,resumePromise=null;
function destroy(){var c=ctx;ctx=null;master=null;resumePromise=null;if(c){try{if(c.state!=='closed')c.close()}catch(e){}}}
function build(){if(!AC)return false;if(ctx&&ctx.state!=='closed')return true;try{ctx=new AC({latencyHint:'interactive'});master=ctx.createGain();master.gain.value=.78;master.connect(ctx.destination);return true}catch(e){destroy();return false}}
function ensure(done){if(!state.enabled){done&&done(false);return}if(!build()){done&&done(false);return}if(ctx.state==='running'){done&&done(true);return}try{if(!resumePromise){var c=ctx;resumePromise=Promise.resolve(c.resume()).then(function(){resumePromise=null;if(c!==ctx){done&&done(false);return}if(c.state==='running'){done&&done(true);return}destroy();if(build()){var c2=ctx;Promise.resolve(c2.resume()).then(function(){done&&done(c2===ctx&&c2.state==='running')}).catch(function(){done&&done(false)})}else done&&done(false)}).catch(function(){resumePromise=null;destroy();done&&done(false)})}else{resumePromise.then(function(){done&&done(!!ctx&&ctx.state==='running')})}}catch(e){destroy();done&&done(false)}}
function tone(f,d,type,v,delay,to){if(!ctx||ctx.state!=='running'||!master||!state.enabled)return;try{var o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+(delay||0);o.type=type||'sine';o.frequency.setValueAtTime(f,t);if(to)o.frequency.exponentialRampToValueAtTime(Math.max(30,to),t+d);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.min(.22,v||.08),t+.003);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(master);o.start(t);o.stop(t+d+.02)}catch(e){}}
function playNow(n){if(n==='tap')tone(520,.025,'sine',.045);else if(n==='start'){tone(330,.055,'sine',.10);tone(495,.08,'sine',.075,.032)}else if(n==='swipe'){tone(190,.03,'triangle',.08,0,280);tone(355,.025,'sine',.045,.012,440)}else if(n==='blocked')tone(125,.05,'triangle',.095,0,92);else if(n==='spawn')tone(300,.038,'sine',.07,0,390);else if(n==='clear'){tone(440,.055,'sine',.125);tone(660,.075,'sine',.10,.022)}else if(n==='combo'){tone(500,.05,'sine',.135);tone(720,.065,'sine',.115,.022);tone(960,.085,'sine',.09,.048)}else if(n==='bigclear'){tone(380,.05,'triangle',.14);tone(620,.075,'sine',.13,.025);tone(900,.09,'sine',.105,.055);tone(1220,.105,'sine',.075,.085)}else if(n==='milestone'){tone(440,.07,'sine',.105);tone(660,.09,'sine',.095,.045);tone(880,.12,'sine',.085,.09)}else if(n==='gameover'){tone(260,.085,'triangle',.10,0,210);tone(180,.12,'triangle',.08,.07,135)}else if(n==='rewind'){tone(720,.055,'sine',.10,0,560);tone(500,.07,'sine',.09,.035,380);tone(340,.09,'sine',.075,.075,240)}}
function play(n){if(!state.enabled)return;ensure(function(ok){if(ok)playNow(n)})}
function prime(){if(state.enabled)ensure()}
document.addEventListener('touchstart',prime,{capture:true,passive:true});document.addEventListener('pointerdown',prime,{capture:true,passive:true});document.addEventListener('click',prime,true);window.addEventListener('pageshow',prime);document.addEventListener('visibilitychange',function(){if(!document.hidden)prime()});
document.addEventListener('fs15soundtoggle',function(e){state.enabled=!!(e.detail&&e.detail.enabled);var b=document.getElementById('soundToggle');if(b)b.classList.toggle('on',state.enabled);if(state.enabled){ensure(function(ok){if(ok)playNow('start')})}else destroy()});
document.addEventListener('fs-sfx',function(e){if(e.detail&&e.detail.name)play(e.detail.name)});
var soundToggle=document.getElementById('soundToggle');if(soundToggle)soundToggle.classList.toggle('on',state.enabled);var musicToggle=document.getElementById('musicToggle');if(musicToggle){var row=musicToggle.closest('.setting');if(row)row.style.display='none'}
var buttons=document.querySelectorAll('button');for(var i=0;i<buttons.length;i++)buttons[i].addEventListener('click',function(){if(this.id!=='soundToggle')play('tap')});
var runGoal=document.getElementById('runGoal'),topGoal=document.getElementById('topGoal');function syncGoal(){if(!runGoal||!topGoal)return;var m=(runGoal.textContent||'').match(/(\d+\s*\/\s*\d+)/);topGoal.textContent=m?m[1].replace(/\s/g,''):'0/15'}if(runGoal&&topGoal){syncGoal();new MutationObserver(syncGoal).observe(runGoal,{childList:true,characterData:true,subtree:true})}
var modeBadge=document.getElementById('modeBadge'),playBtn=document.getElementById('playBtn'),dailyBtn=document.getElementById('dailyBtn');if(playBtn)playBtn.addEventListener('click',function(){if(modeBadge)modeBadge.textContent='CLASSIC'});if(dailyBtn)dailyBtn.addEventListener('click',function(){if(modeBadge)modeBadge.textContent='DAILY • HARD'});
var style=document.createElement('style');style.textContent='.piece.active{filter:saturate(1.08) brightness(1.12)!important;box-shadow:inset 0 2px 5px rgba(255,255,255,.40),inset 0 -5px 9px rgba(0,0,0,.20),0 5px 12px rgba(0,0,0,.25),0 0 0 2px rgba(255,255,255,.12),0 0 8px var(--glow),0 0 14px var(--glow)!important}.piece.active:before{opacity:.14!important;inset:-6%!important;border-width:1px!important}@keyframes activePulseLive{0%,100%{filter:saturate(1.06) brightness(1.09)}50%{filter:saturate(1.12) brightness(1.16)}}';document.head.appendChild(style);
})();