(function(){
'use strict';
function replaceBetween(src,start,end,replacement){var a=src.indexOf(start),b=src.indexOf(end,a);if(a<0||b<0)throw new Error('Patch marker missing: '+start);return src.slice(0,a)+replacement+src.slice(b)}
function patchCore(src){
  src=src.replace("function cleanNum(v){v=Number(v);return Number.isFinite(v)&&v>=0?v:0}","function cleanNum(v){v=Number(v);return Number.isFinite(v)&&v>=0?v:0}\nfunction emitSound(name){try{document.dispatchEvent(new CustomEvent('fs-sfx',{detail:{name:name}}))}catch(e){}}")
  var fair=`function hasColor(color){var yes=false;eachBall(function(id,b){if(b.color===color)yes=true});return yes}
function colorCount(color){var n=0;eachBall(function(id,b){if(b.color===color)n++});return n}
function legalColor(color){var yes=false,ds=[[1,0],[-1,0],[0,1],[0,-1]];eachBall(function(id,b){if(yes||b.color!==color)return;for(var d=0;d<4;d++){var nx=b.x+ds[d][0],ny=b.y+ds[d][1];if(nx>=0&&nx<N&&ny>=0&&ny<N&&grid[ny][nx]===null){yes=true;return}}});return yes}
function colorMobility(color){var score=0,ds=[[1,0],[-1,0],[0,1],[0,-1]];eachBall(function(id,b){if(b.color!==color)return;for(var d=0;d<4;d++){var nx=b.x+ds[d][0],ny=b.y+ds[d][1];if(nx>=0&&nx<N&&ny>=0&&ny<N&&grid[ny][nx]===null)score++}});return score}
function colorPlayable(color){return colorCount(color)>=3&&legalColor(color)}
function playableColors(){var out=[],n=colorsInPlay();for(var c=0;c<n;c++)if(colorPlayable(c))out.push(c);return out}
function nextPlayable(from){var c=from,n=colorsInPlay();for(var i=0;i<n;i++){c=(c+1)%n;if(colorPlayable(c))return c}return -1}
function evaluateSpawnCandidate(x,y,color,beforePlayable,beforeCounts){var fake=-999999;while(balls[fake])fake--;grid[y][x]=fake;balls[fake]={x:x,y:y,color:color};var afterPlayable=playableColors(),preserves=true;for(var i=0;i<beforePlayable.length;i++)if(afterPlayable.indexOf(beforePlayable[i])<0){preserves=false;break}var introducesThird=beforeCounts[color]===2,introducedPlayable=!introducesThird||afterPlayable.indexOf(color)>=0;var mobility=0;for(var c=0;c<colorsInPlay();c++)if(colorCount(c)>=3)mobility+=colorMobility(c);var open=0,ds=[[1,0],[-1,0],[0,1],[0,-1]];for(var d=0;d<4;d++){var nx=x+ds[d][0],ny=y+ds[d][1];if(nx>=0&&nx<N&&ny>=0&&ny<N&&grid[ny][nx]===null)open++}delete balls[fake];grid[y][x]=null;return{preserves:preserves,introducedPlayable:introducedPlayable,playableCount:afterPlayable.length,mobility:mobility,open:open}}
function spawnOne(forcedColor){var e=emptyCells();if(!e.length)return null;var cs=counts(),numColors=colorsInPlay(),beforePlayable=playableColors(),preferred=[],fallback=[],diff=currentDifficulty();for(var i=0;i<e.length;i++){var start=forcedColor===undefined?0:forcedColor,end=forcedColor===undefined?numColors:forcedColor+1;for(var color=start;color<end;color++){var x=e[i][0],y=e[i][1],size=groupSizeIfPlaced(x,y,color);if(size>=3)continue;var ev=evaluateSpawnCandidate(x,y,color,beforePlayable,cs),avg=ballCount()/numColors,balance=(avg-cs[color])*.55,shortage=cs[color]<3?(3-cs[color])*2.4:0,pairBias=size===2?(diff==='normal'?.35:-.25):0,edge=(x===0||x===N-1||y===0||y===N-1)?.22:0,randomness=rng()*(diff==='normal'?.18:.42),v=ev.playableCount*5+ev.mobility*.09+ev.open*.38+balance+shortage+pairBias+edge+randomness;var item={x:x,y:y,color:color,v:v};fallback.push(item);if(ev.preserves&&ev.introducedPlayable)preferred.push(item)}}var pool=preferred.length?preferred:fallback;if(!pool.length){var p=e[0];return addBall(p[0],p[1],forcedColor===undefined?0:forcedColor)}pool.sort(function(a,b){return b.v-a.v});var pick=pool[0];return addBall(pick.x,pick.y,pick.color)}
function seedBoard(){for(var attempt=0;attempt<240;attempt++){grid=[];for(var y=0;y<N;y++){grid[y]=[];for(var x=0;x<N;x++)grid[y][x]=null}balls={};nextId=1;var diff=currentDifficulty(),initial=diff==='expert'?18:diff==='hard'?17:16;for(var k=0;k<initial;k++){var e=emptyCells(),p=e[Math.floor(rng()*e.length)],c=k%3;addBall(p[0],p[1],c)}var healthy=!findGroups(0).length&&!findGroups(1).length&&!findGroups(2).length;for(var c=0;c<3&&healthy;c++)healthy=colorPlayable(c)&&colorMobility(c)>=2;if(healthy)return}}
`;
  fair=fair.replace("diff==='normal'?.35:-.25","diff==='normal' ? .35 : -.25").replace("diff==='normal'?.18:.42","diff==='normal' ? .18 : .42").replace("edge=(x===0||x===N-1||y===0||y===N-1)?.22:0","edge=(x===0||x===N-1||y===0||y===N-1) ? .22 : 0");
  src=replaceBetween(src,'function spawnOne()','function fieldVars',fair);
  src=src.replace("function introduceViolet(){var want=3;for(var i=0;i<want;i++){var id=spawnOne();if(id!==null){balls[id].color=3}}render()}","function introduceViolet(){var want=3;for(var i=0;i<want;i++)spawnOne(3);render()}");
  src=src.replace("function advanceFieldImmediately(){var oldActive=active;var candidate=nextPlayable(colorCursor);if(candidate>=0){active=candidate;colorCursor=candidate;fieldVars(active);fieldName.textContent=COLORS[active].name;var next=nextPlayable(colorCursor);if(next<0)next=active;nextDot.style.background=COLORS[next].c;nextDot.style.color=COLORS[next].c;renderActiveOnly(oldActive)}}","function nextPlayableAfterClear(from,clearIds){var saved=[];for(var i=0;i<clearIds.length;i++){var id=clearIds[i],b=balls[id];if(!b)continue;saved.push([id,b]);grid[b.y][b.x]=null;delete balls[id]}var next=nextPlayable(from);for(var j=0;j<saved.length;j++){var row=saved[j],bid=row[0],bb=row[1];balls[bid]=bb;grid[bb.y][bb.x]=bid}return next}\nfunction advanceFieldImmediately(clearIds){var oldActive=active;var candidate=nextPlayableAfterClear(colorCursor,clearIds||[]);if(candidate>=0){active=candidate;colorCursor=candidate;fieldVars(active);fieldName.textContent=COLORS[active].name;var next=nextPlayableAfterClear(colorCursor,clearIds||[]);if(next<0)next=active;nextDot.style.background=COLORS[next].c;nextDot.style.color=COLORS[next].c;renderActiveOnly(oldActive)}}");
  src=src.replace('advanceFieldImmediately();setTimeout(function(){','advanceFieldImmediately(clear);setTimeout(function(){');
  src=src.replace('var currentValid=hasColor(active)&&legalColor(active);','var currentValid=colorPlayable(active);');
  src=src.replace("sfx('milestone');unlockAchievement","sfx('milestone');emitSound('milestone');unlockAchievement");
  src=src.replace("sfx('blocked');haptic('error')","sfx('blocked');emitSound('blocked');haptic('error')");
  src=src.replace("sfx('swipe');haptic('light');","sfx('swipe');emitSound('swipe');haptic('light');");
  src=src.replace("sfx(clear.length>=5?'bigclear':combo>=2?'combo':'clear');haptic","sfx(clear.length>=5?'bigclear':combo>=2?'combo':'clear');emitSound(clear.length>=5?'bigclear':combo>=2?'combo':'clear');haptic");
  src=src.replace("render([id]);sfx('spawn');setTimeout","render([id]);sfx('spawn');emitSound('spawn');setTimeout");
  src=src.replace("if(settings.music)startAmbience();sfx('start')}","if(settings.music)startAmbience();sfx('start');emitSound('start')}");
  src=src.replace("sfx('gameover');haptic('error');","sfx('gameover');emitSound('gameover');haptic('error');");
  src=src.replace("showToast('FIELD REWOUND');sfx('rewind')}","showToast('FIELD REWOUND');sfx('rewind');emitSound('rewind')}");
  return src;
}
function loadScript(src){return new Promise(function(resolve,reject){var s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.body.appendChild(s)})}
fetch('game11.js?t='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('core '+r.status);return r.text()}).then(function(src){var patched=patchCore(src);(0,eval)(patched);return loadScript('live14.js?t='+Date.now())}).catch(function(err){console.error('FieldShift Build 14 failed',err);var v=document.querySelector('.version');if(v)v.textContent='BUILD ERROR • REFRESH';});
})();
