(function(){
'use strict';
var state=window.__FS12_SOUND__||{enabled:true};
var AC=window.AudioContext||window.webkitAudioContext;
var ctx=null,master=null,limiter=null,bus=null,generation=0,resuming=null;
var lastScore=0,spawnTimer=null;
function destroy(){var old=ctx;ctx=master=limiter=bus=null;resuming=null;if(old){try{if(old.state!=='closed')old.close()}catch(e){}}}
function build(force){if(force)destroy();if(ctx&&ctx.state!=='closed')return true;if(!AC)return false;try{ctx=new AC({latencyHint:'interactive'});generation++;master=ctx.createGain();bus=ctx.createGain();limiter=ctx.createDynamicsCompressor();master.gain.value=.92;bus.gain.value=.82;limiter.threshold.value=-8;limiter.knee.value=6;limiter.ratio.value=12;limiter.attack.value=.002;limiter.release.value=.12;bus.connect(master);master.connect(limiter);limiter.connect(ctx.destination);return true}catch(e){destroy();return false}}
function ensure(done,retry){retry=retry||0;if(!state.enabled){if(done)done(false);return}if(!build(false)){if(done)done(false);return}if(ctx.state==='running'){if(done)done(true);return}var c=ctx,g=generation;try{var p=c.resume();resuming=Promise.resolve(p).then(function(){resuming=null;if(c!==ctx||g!==generation)return;if(c.state==='running'){if(done)done(true)}else if(retry<1){build(true);ensure(done,retry+1)}else if(done)done(false)}).catch(function(){resuming=null;if(retry<1){build(true);ensure(done,retry+1)}else if(done)done(false)})}catch(e){if(retry<1){build(true);ensure(done,retry+1)}else if(done)done(false)}}
function tone(f,d,type,v,delay){if(!ctx||ctx.state!=='running'||!bus)return;var o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+(delay||0);o.type=type||'sine';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.min(.28,v||.08),t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(bus);o.start(t);o.stop(t+d+.02)}
function play(name){if(!state.enabled)return;ensure(function(ok){if(!ok)return;switch(name){case'tap':tone(340,.025,'sine',.045);break;case'start':tone(330,.06,'sine',.12);tone(495,.09,'sine',.095,.035);break;case'swipe':tone(170,.03,'triangle',.06);tone(250,.018,'sine',.03,.009);break;case'blocked':tone(120,.05,'triangle',.08);tone(90,.035,'sine',.04,.018);break;case'spawn':tone(300,.04,'sine',.07);tone(440,.03,'sine',.03,.014);break;case'clear':tone(450,.055,'sine',.145);tone(675,.085,'sine',.11,.022);break;case'combo':tone(520,.05,'sine',.15);tone(790,.075,'sine',.13,.022);tone(1060,.095,'sine',.09,.048);break;case'milestone':tone(440,.08,'sine',.12);tone(660,.11,'sine',.12,.05);tone(880,.14,'sine',.1,.1);break;case'gameover':tone(270,.09,'triangle',.11);tone(195,.13,'triangle',.09,.07);tone(145,.18,'sine',.065,.15);break;case'rewind':tone(720,.055,'sine',.11);tone(540,.065,'sine',.1,.035);tone(380,.09,'sine',.08,.075);break;}})}
function recover(){if(!state.enabled)return;if(!ctx||ctx.state==='closed')build(true);ensure()}
document.addEventListener('touchstart',recover,{passive:true});document.addEventListener('pointerdown',recover,{passive:true});window.addEventListener('pageshow',recover);document.addEventListener('visibilitychange',function(){if(!document.hidden)recover()});
document.addEventListener('fs12soundtoggle',function(e){state.enabled=!!(e.detail&&e.detail.enabled);var b=document.getElementById('soundToggle');if(b)b.classList.toggle('on',state.enabled);if(state.enabled){recover();play('start')}else destroy()});
var soundToggle=document.getElementById('soundToggle');if(soundToggle){soundToggle.classList.toggle('on',state.enabled);new MutationObserver(function(){soundToggle.classList.toggle('on',state.enabled)}).observe(soundToggle,{attributes:true,attributeFilter:['class']})}
var musicToggle=document.getElementById('musicToggle');if(musicToggle){var row=musicToggle.closest('.setting');if(row)row.style.display='none'}
var area=document.getElementById('gestureArea');if(area){area.addEventListener('touchend',function(e){if(e.changedTouches&&e.changedTouches.length)play('swipe')},{passive:true});area.addEventListener('mouseup',function(){play('swipe')})}
var board=document.getElementById('board');if(board)new MutationObserver(function(ms){for(var i=0;i<ms.length;i++)if(ms[i].attributeName==='class'&&board.classList.contains('shake')){play('blocked');break}}).observe(board,{attributes:true,attributeFilter:['class']});
var score=document.getElementById('score');if(score){lastScore=Number(score.textContent)||0;new MutationObserver(function(){var n=Number(score.textContent)||0;if(n>lastScore){var toast=document.getElementById('toast'),t=toast?toast.textContent:'';play(t.indexOf('COMBO')>=0?'combo':'clear')}lastScore=n}).observe(score,{childList:true,characterData:true,subtree:true})}
var grid=document.getElementById('grid');if(grid)new MutationObserver(function(){if(grid.querySelector('.piece.spawn')){clearTimeout(spawnTimer);spawnTimer=setTimeout(function(){play('spawn')},10)}}).observe(grid,{childList:true,subtree:true});
var result=document.getElementById('resultModal');if(result)new MutationObserver(function(){if(result.classList.contains('show'))play('gameover')}).observe(result,{attributes:true,attributeFilter:['class']});
var milestone=document.getElementById('milestone');if(milestone)new MutationObserver(function(){if(milestone.classList.contains('show'))play('milestone')}).observe(milestone,{attributes:true,attributeFilter:['class']});
var game=document.getElementById('game');if(game)new MutationObserver(function(){if(game.classList.contains('show')){lastScore=0;play('start')}}).observe(game,{attributes:true,attributeFilter:['class']});
var rewind=document.getElementById('rewindBtn');if(rewind)rewind.addEventListener('click',function(){play('rewind')});
var buttons=document.querySelectorAll('button');for(var i=0;i<buttons.length;i++)buttons[i].addEventListener('click',function(e){if(this.id!=='soundToggle'&&this.id!=='rewindBtn')play('tap')});
})();