(function(){
'use strict';
var N=6, MOVE_MS=140, CLEAR_MS=165, LOW_FLOOR=6;
var COLORS=[
 {name:'BLUE',c:'#57a7ff',light:'#a6d4ff',dark:'#285fc1',glow:'rgba(87,167,255,.48)',rgb:'87,167,255'},
 {name:'PINK',c:'#ff5e9f',light:'#ffafd2',dark:'#c62d6c',glow:'rgba(255,94,159,.45)',rgb:'255,94,159'},
 {name:'GOLD',c:'#ffc84b',light:'#ffe59c',dark:'#c78918',glow:'rgba(255,200,75,.42)',rgb:'255,200,75'}
];
function $(id){return document.getElementById(id)}
var menu=$('menu'),game=$('game'),gridEl=$('grid'),board=$('board'),scoreEl=$('score'),menuBest=$('menuBest'),bestMini=$('bestMini');
var fieldOrb=$('fieldOrb'),fieldName=$('fieldName'),nextDot=$('nextDot'),pips=$('pips'),coach=$('coach'),sweep=$('sweep'),toast=$('toast');
var fieldCard=document.querySelector('.field-card');
var pauseModal=$('pauseModal'),resultModal=$('resultModal'),howModal=$('howModal'),settingsModal=$('settingsModal'),adOverlay=$('adOverlay');
var cells=[];for(var i=0;i<36;i++){var cell=document.createElement('div');cell.className='cell';gridEl.appendChild(cell);cells.push(cell)}
var grid,balls,nextId,active,colorCursor,score,combo,turns,pressure,locked,ended,paused,revived,history,runCount=0,motion=true;
var best=0;try{best=Number(localStorage.getItem('fieldshift-best')||0)}catch(e){}menuBest.textContent=best;bestMini.textContent=best;
function haptic(kind){var p=kind==='invalid'?12:kind==='move'?8:kind==='spawn'?10:kind==='clear'?[18,18,28]:kind==='combo'?[18,14,34,12,44]:kind==='gameover'?[36,25,58]:8;try{if(navigator.vibrate)navigator.vibrate(p)}catch(e){}}
function eachBall(fn){for(var id in balls)if(Object.prototype.hasOwnProperty.call(balls,id))fn(Number(id),balls[id])}
function clone(v){return JSON.parse(JSON.stringify(v))}
function snapshot(){return{grid:clone(grid),balls:clone(balls),nextId:nextId,active:active,colorCursor:colorCursor,score:score,combo:combo,turns:turns,pressure:pressure}}
function restore(s){grid=clone(s.grid);balls=clone(s.balls);nextId=s.nextId;active=s.active;colorCursor=s.colorCursor;score=s.score;combo=s.combo;turns=s.turns;pressure=s.pressure;ended=false;paused=false;locked=false;resultModal.classList.remove('show');render();updateUI();haptic('clear')}
function emptyCells(){var a=[];for(var y=0;y<N;y++)for(var x=0;x<N;x++)if(grid[y][x]===null)a.push([x,y]);return a}
function ballCount(){var n=0;eachBall(function(){n++});return n}
function counts(){var a=[0,0,0];eachBall(function(id,b){a[b.color]++});return a}
function addBall(x,y,color){var id=nextId++;grid[y][x]=id;balls[id]={x:x,y:y,color:color};return id}
function styleBall(el,b){var c=COLORS[b.color];el.style.setProperty('--c',c.c);el.style.setProperty('--light',c.light);el.style.setProperty('--dark',c.dark);el.style.setProperty('--glow',c.glow)}
function render(spawned){spawned=spawned||[];for(var i=0;i<cells.length;i++)cells[i].innerHTML='';eachBall(function(id,b){var el=document.createElement('div');el.className='piece';el.dataset.id=String(id);styleBall(el,b);if(b.color===active)el.classList.add('active');if(spawned.indexOf(id)>=0)el.classList.add('spawn');cells[b.y*N+b.x].appendChild(el)})}
function capture(){var out={},els=gridEl.querySelectorAll('.piece');for(var i=0;i<els.length;i++){var r=els[i].getBoundingClientRect();out[els[i].dataset.id]={x:r.left,y:r.top}}return out}
function animateMove(old){if(!motion||!old)return;requestAnimationFrame(function(){var els=gridEl.querySelectorAll('.piece');for(var i=0;i<els.length;i++){var o=old[els[i].dataset.id];if(!o)continue;var r=els[i].getBoundingClientRect(),dx=o.x-r.left,dy=o.y-r.top;if(Math.abs(dx)<1&&Math.abs(dy)<1)continue;if(els[i].animate)els[i].animate([{transform:'translate3d('+dx+'px,'+dy+'px,0) scale(.96)'},{transform:'translate3d(0,0,0) scale(1.035)',offset:.82},{transform:'translate3d(0,0,0) scale(1)'}],{duration:MOVE_MS,easing:'cubic-bezier(.16,.84,.28,1)'})}})}
function findGroups(color){var seen={},clear=[];eachBall(function(id,b){if(b.color!==color||seen[id])return;var q=[id],group=[];seen[id]=1;while(q.length){var cid=q.pop(),cb=balls[cid];group.push(cid);var dirs=[[1,0],[-1,0],[0,1],[0,-1]];for(var d=0;d<4;d++){var nx=cb.x+dirs[d][0],ny=cb.y+dirs[d][1];if(nx<0||nx>=N||ny<0||ny>=N)continue;var nid=grid[ny][nx],nb=nid!==null?balls[nid]:null;if(nb&&nb.color===color&&!seen[nid]){seen[nid]=1;q.push(nid)}}}if(group.length>=3)clear=clear.concat(group)});return clear}
function groupSizeIfPlaced(x,y,color){var fake=999999;grid[y][x]=fake;balls[fake]={x:x,y:y,color:color};var q=[fake],seen={999999:1},size=0;while(q.length){var id=q.pop(),b=balls[id];size++;var dirs=[[1,0],[-1,0],[0,1],[0,-1]];for(var d=0;d<4;d++){var nx=b.x+dirs[d][0],ny=b.y+dirs[d][1];if(nx<0||nx>=N||ny<0||ny>=N)continue;var nid=grid[ny][nx],nb=nid!==null?balls[nid]:null;if(nb&&nb.color===color&&!seen[nid]){seen[nid]=1;q.push(nid)}}}delete balls[fake];grid[y][x]=null;return size}
function spawnOne(){var e=emptyCells();if(!e.length)return null;var cs=counts(),min=Math.min.apply(null,cs),occ=ballCount()/36,opts=[];for(var i=0;i<e.length;i++)for(var color=0;color<3;color++){var x=e[i][0],y=e[i][1],size=groupSizeIfPlaced(x,y,color);if(size>=3)continue;var open=0,dirs=[[1,0],[-1,0],[0,1],[0,-1]];for(var d=0;d<4;d++){var nx=x+dirs[d][0],ny=y+dirs[d][1];if(nx>=0&&nx<N&&ny>=0&&ny<N&&grid[ny][nx]===null)open++}var value=(cs[color]===min?1.35:0)+(size===2?1.15:0)+open*.22+Math.random()*2.4;if(occ>.72)value+=open*.35;opts.push({x:x,y:y,color:color,v:value})}var pick;if(opts.length){opts.sort(function(a,b){return b.v-a.v});var top=opts.slice(0,Math.min(12,opts.length));pick=top[Math.floor(Math.random()*top.length)]}else{var p=e[Math.floor(Math.random()*e.length)];pick={x:p[0],y:p[1],color:Math.floor(Math.random()*3)}}return addBall(pick.x,pick.y,pick.color)}
function seed(){for(var attempt=0;attempt<120;attempt++){grid=[];for(var y=0;y<N;y++){grid[y]=[];for(var x=0;x<N;x++)grid[y][x]=null}balls={};nextId=1;for(var c=0;c<3;c++)for(var k=0;k<5;k++){var e=emptyCells(),p=e[Math.floor(Math.random()*e.length)];addBall(p[0],p[1],c)}if(!findGroups(0).length&&!findGroups(1).length&&!findGroups(2).length)return}}
function hasColor(color){var yes=false;eachBall(function(id,b){if(b.color===color)yes=true});return yes}
function legalColor(color){var yes=false,dirs=[[1,0],[-1,0],[0,1],[0,-1]];eachBall(function(id,b){if(yes||b.color!==color)return;for(var d=0;d<4;d++){var nx=b.x+dirs[d][0],ny=b.y+dirs[d][1];if(nx>=0&&nx<N&&ny>=0&&ny<N&&grid[ny][nx]===null){yes=true;return}}});return yes}
function nextPlayable(from){var c=from;for(var i=0;i<3;i++){c=(c+1)%3;if(hasColor(c)&&legalColor(c))return c}return -1}
function updateFieldTheme(){var c=COLORS[active];fieldCard.style.transition='background .24s ease,border-color .24s ease,box-shadow .24s ease';fieldCard.style.background='linear-gradient(135deg,rgba('+c.rgb+',.18),rgba('+c.rgb+',.055))';fieldCard.style.borderColor='rgba('+c.rgb+',.24)';fieldCard.style.boxShadow='inset 0 1px rgba(255,255,255,.045),0 0 24px rgba('+c.rgb+',.055)'}
function updateUI(){scoreEl.textContent=score;menuBest.textContent=best;bestMini.textContent=best;var c=COLORS[active];fieldOrb.style.background='radial-gradient(circle at 32% 25%,white 0 5%,'+c.light+' 13%,'+c.c+' 55%,'+c.dark+' 100%)';fieldOrb.style.color=c.c;fieldName.textContent=c.name;updateFieldTheme();var next=nextPlayable(colorCursor);if(next<0)next=active;nextDot.style.background=COLORS[next].c;var ps=pips.children,threshold=pressureThreshold();for(var i=0;i<ps.length;i++)ps[i].className=(i<pressure?'on ':'')+(pressure>=threshold-1&&i<pressure?'hot':'')}
function performMove(dx,dy){var list=[];eachBall(function(id,b){if(b.color===active)list.push({id:id,b:b,ox:b.x,oy:b.y})});list.sort(function(a,b){if(dx<0)return a.ox-b.ox;if(dx>0)return b.ox-a.ox;if(dy<0)return a.oy-b.oy;return b.oy-a.oy});var moved=false;for(var i=0;i<list.length;i++){var it=list[i],b=it.b;grid[b.y][b.x]=null;var x=b.x,y=b.y;while(true){var nx=x+dx,ny=y+dy;if(nx<0||nx>=N||ny<0||ny>=N||grid[ny][nx]!==null)break;x=nx;y=ny}b.x=x;b.y=y;grid[y][x]=it.id;if(x!==it.ox||y!==it.oy)moved=true}return moved}
function pressureThreshold(){if(ballCount()<=10)return 2;return turns>=28?2:3}
function spawnCount(){pressure++;var t=pressureThreshold();if(pressure>=t){pressure=0;return 2}return 1}
function fieldFlash(dx,dy){var c=COLORS[active],angle=dx>0?'to right':dx<0?'to left':dy>0?'to bottom':'to top';sweep.style.background='linear-gradient('+angle+',transparent 5%,rgba('+c.rgb+',.28),rgba(255,255,255,.10),transparent 76%)';sweep.classList.remove('go');void sweep.offsetWidth;sweep.classList.add('go')}
function bump(){board.classList.remove('shake');void board.offsetWidth;board.classList.add('shake');haptic('invalid')}
function showToast(t){toast.textContent=t;toast.classList.remove('show');void toast.offsetWidth;toast.classList.add('show')}
function stabilizeAfterClear(done){var need=Math.min(2,Math.max(0,LOW_FLOOR-ballCount()));if(!need){done();return}spawnMany(need,0,function(){showToast('FIELD RECHARGED');done()})}
function resolveSwipe(dx,dy){if(locked||ended||paused)return;locked=true;var before=snapshot(),old=capture();if(!performMove(dx,dy)){locked=false;bump();return}haptic('move');history.push(before);if(history.length>10)history.shift();turns++;coach.style.opacity=turns>1?'0':'1';fieldFlash(dx,dy);render();animateMove(old);setTimeout(function(){var clear=findGroups(active);if(clear.length){combo++;pressure=Math.max(0,pressure-1);var gain=clear.length*10*combo;score+=gain;showToast('+'+gain+(combo>1?' • COMBO ×'+combo:''));haptic(combo>1?'combo':'clear');for(var i=0;i<clear.length;i++){var el=gridEl.querySelector('[data-id="'+clear[i]+'"]');if(el)el.classList.add('clear')}setTimeout(function(){for(var j=0;j<clear.length;j++){var b=balls[clear[j]];if(b){grid[b.y][b.x]=null;delete balls[clear[j]]}}render();stabilizeAfterClear(finishTurn)},CLEAR_MS)}else{combo=0;spawnMany(spawnCount(),0,finishTurn)}},MOVE_MS+12)}
function spawnMany(total,index,done){if(index>=total){if(done)done();return}var id=spawnOne();if(id===null){endGame();return}haptic('spawn');render([id]);setTimeout(function(){spawnMany(total,index+1,done)},82)}
function finishTurn(){if(score>best){best=score;saveBest()}var next=nextPlayable(colorCursor);if(next<0){endGame();return}active=next;colorCursor=next;render();updateUI();locked=false}
function saveBest(){try{localStorage.setItem('fieldshift-best',best)}catch(e){}}
function startGame(){seed();score=0;combo=0;turns=0;pressure=0;locked=false;ended=false;paused=false;revived=false;history=[];colorCursor=-1;active=nextPlayable(-1);if(active<0)active=0;colorCursor=active;menu.classList.remove('show');pauseModal.classList.remove('show');resultModal.classList.remove('show');game.classList.add('show');coach.style.opacity='1';render();updateUI();haptic('move')}
function endGame(){ended=true;locked=false;runCount++;haptic('gameover');var isNew=score>best;if(isNew){best=score;saveBest()}updateUI();$('resultScore').textContent=score;$('resultMeta').textContent=turns+' swipes • '+ballCount()+' balls left';$('newBest').style.display=isNew?'block':'none';$('rewindBtn').style.display=!revived&&history.length>=3?'block':'none';setTimeout(function(){resultModal.classList.add('show')},180)}
function showMenu(){ended=true;paused=false;game.classList.remove('show');pauseModal.classList.remove('show');resultModal.classList.remove('show');menu.classList.add('show');menuBest.textContent=best}
function rewind(){if(revived||history.length<3)return;var s=history[Math.max(0,history.length-3)];restore(s);revived=true;history=[];showToast('FIELD REWOUND')}
var pendingAd=null,adType='',adTimer=null;
function showAd(type,callback){if(adOverlay.classList.contains('show'))return;pendingAd=callback||null;adType=type;var seconds=type==='rewarded'?4:3;$('adLabel').textContent='DEMO AD • '+(type==='open'?'APP OPEN':type.toUpperCase());$('adFoot').textContent=type==='rewarded'?'Watch to the end to earn the rewind.':'No network request is made.';var close=$('adClose'),bar=$('adBar');close.disabled=true;close.textContent=String(seconds);bar.style.transition='none';bar.style.width='0';adOverlay.classList.add('show');requestAnimationFrame(function(){requestAnimationFrame(function(){bar.style.transition='width '+seconds+'s linear';bar.style.width='100%'})});var left=seconds;if(adTimer)clearInterval(adTimer);adTimer=setInterval(function(){left--;if(left>0)close.textContent=String(left);else{clearInterval(adTimer);adTimer=null;close.disabled=false;close.textContent=type==='rewarded'?'CLAIM':'×'}},1000)}
function closeAd(){var close=$('adClose');if(close.disabled)return;var cb=pendingAd;pendingAd=null;var type=adType;adType='';adOverlay.classList.remove('show');if(cb)cb(type)}
$('adClose').addEventListener('click',closeAd);$('playBtn').addEventListener('click',function(){haptic('move');startGame()});$('pauseBtn').addEventListener('click',function(){if(locked)return;haptic('move');paused=true;pauseModal.classList.add('show')});$('continueBtn').addEventListener('click',function(){haptic('move');paused=false;pauseModal.classList.remove('show')});$('restartBtn').addEventListener('click',startGame);$('homeBtn').addEventListener('click',showMenu);$('resultHomeBtn').addEventListener('click',showMenu);$('againBtn').addEventListener('click',function(){resultModal.classList.remove('show');if(runCount>0&&runCount%3===0)showAd('interstitial',startGame);else startGame()});$('rewindBtn').addEventListener('click',function(){showAd('rewarded',rewind)});$('howBtn').addEventListener('click',function(){howModal.classList.add('show')});$('closeHowBtn').addEventListener('click',function(){howModal.classList.remove('show')});$('settingsBtn').addEventListener('click',function(){settingsModal.classList.add('show')});$('closeSettingsBtn').addEventListener('click',function(){settingsModal.classList.remove('show')});$('motionToggle').addEventListener('click',function(){motion=!motion;this.classList.toggle('on',motion)});$('testOpen').addEventListener('click',function(){showAd('open')});$('testInter').addEventListener('click',function(){showAd('interstitial')});$('testReward').addEventListener('click',function(){showAd('rewarded')});
var sx=0,sy=0,drag=false,area=$('gestureArea');function begin(x,y){sx=x;sy=y;drag=true}function finish(x,y){if(!drag)return;drag=false;var dx=x-sx,dy=y-sy;if(Math.sqrt(dx*dx+dy*dy)<26){bump();return}if(Math.abs(dx)>Math.abs(dy))resolveSwipe(dx>0?1:-1,0);else resolveSwipe(0,dy>0?1:-1)}
area.addEventListener('touchstart',function(e){var t=e.changedTouches[0];begin(t.clientX,t.clientY);e.preventDefault()},{passive:false});area.addEventListener('touchend',function(e){var t=e.changedTouches[0];finish(t.clientX,t.clientY);e.preventDefault()},{passive:false});area.addEventListener('touchcancel',function(){drag=false});area.addEventListener('mousedown',function(e){begin(e.clientX,e.clientY)});window.addEventListener('mouseup',function(e){finish(e.clientX,e.clientY)});window.addEventListener('error',function(e){console.error(e.error||e.message)});
})();
